import { useState, useEffect, useCallback, useRef } from "react";
import { supabase } from "./supabase";
import { useAuth } from "./auth-context";
import {
  encryptMessage,
  decryptMessage,
  encryptSealedSenderMessage,
  decryptSealedSenderMessage,
  onFriendConfirmed,
  onFriendRemoved,
} from "./crypto";
import { toast } from "sonner";
import type { Profile, Post, Message, FriendRequest, LiveStream, Notification, Conversation } from "./supabase-types";
import { interestById, courseById, splitList, countMatches, textMatchesTerm } from "./interests";

// ─── FEED HOOKS ─────────────────────────────────────────────────

export interface PostWithDetails extends Post {
  profiles: Pick<Profile, "id" | "name" | "department" | "year" | "status" | "avatar_url">;
  like_count: number;
  comment_count: number;
  is_liked_by_me: boolean;
}

export function useFeedPosts() {
  const [posts, setPosts] = useState<PostWithDetails[]>([]);
  const [loading, setLoading] = useState(true);
  const { isAuthenticated } = useAuth();

  // Notifications are generated by database triggers so they work no matter
  // which client (web, Android, a future backend job) performed the action.
  const notify = async (
    recipientId: string,
    actorId: string,
    type: string,
    title: string,
    body: string
  ) => {
    if (!recipientId || recipientId === actorId) return;
    const { error } = await (supabase.from("notifications") as any).insert({
      user_id: recipientId,
      actor_id: actorId,
      type,
      title,
      body,
    });
    if (error) console.error("Failed to create notification:", error.message);
  };

  const fetchPosts = useCallback(async () => {
    setLoading(true);
    try {
      const { data: rawData, error } = await supabase
        .from("posts")
        .select(`
          *,
          profiles!inner(id, name, department, year, status, avatar_url)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;
      const data: any[] = rawData ?? [];

      const postsWithMeta = await Promise.all(
        data.map(async (post: any) => {
          const { count: likeCount } = await supabase
            .from("post_likes")
            .select("*", { count: "exact", head: true })
            .eq("post_id", post.id);

          const { count: commentCount } = await supabase
            .from("comments")
            .select("*", { count: "exact", head: true })
            .eq("post_id", post.id);

          let isLikedByMe = false;
          if (isAuthenticated) {
            const { data: sessionData } = await supabase.auth.getSession();
            if (sessionData?.session?.user) {
              const { data: like } = await supabase
                .from("post_likes")
                .select("id")
                .eq("post_id", post.id)
                .eq("user_id", sessionData.session.user.id)
                .maybeSingle();
              isLikedByMe = !!like;
            }
          }

          return {
            ...post,
            like_count: likeCount ?? 0,
            comment_count: commentCount ?? 0,
            is_liked_by_me: isLikedByMe,
          } as PostWithDetails;
        })
      );

      setPosts(postsWithMeta);
    } catch (err) {
      console.error("Failed to fetch posts:", err);
    } finally {
      setLoading(false);
    }
  }, [isAuthenticated]);

  useEffect(() => {
    fetchPosts();
  }, [fetchPosts]);

  const likePost = async (postId: string) => {
    const { data: sessionData } = await supabase.auth.getSession();
    if (!sessionData?.session?.user) return;
    const uid = sessionData.session.user.id;

    const existing = await supabase
      .from("post_likes")
      .select("id")
      .eq("post_id", postId)
      .eq("user_id", uid)
      .maybeSingle();

    if (existing.data) {
      await supabase.from("post_likes").delete().eq("id", (existing.data as any).id);
    } else {
      await supabase.from("post_likes").insert({ post_id: postId, user_id: uid } as any);

      // Send notification to post author
      const postRes = await (supabase.from("posts") as any).select("user_id").eq("id", postId).single();
      if (postRes.data) {
        const myProfileRes = await (supabase.from("profiles") as any).select("name").eq("id", uid).single();
        await notify(
          postRes.data.user_id,
          uid,
          "like",
          "New Like",
          `${myProfileRes.data?.name ?? "Someone"} liked your post.`
        );
      }
    }
    fetchPosts();
  };

  const addComment = async (postId: string, content: string) => {
    const { data: sessionData } = await supabase.auth.getSession();
    if (!sessionData?.session?.user) return;
    const uid = sessionData.session.user.id;
    await supabase.from("comments").insert({
      post_id: postId,
      user_id: uid,
      content,
    } as any);

    // Send notification to post author
    const postRes = await (supabase.from("posts") as any).select("user_id").eq("id", postId).single();
    if (postRes.data) {
      const myProfileRes = await (supabase.from("profiles") as any).select("name").eq("id", uid).single();
      await notify(
        postRes.data.user_id,
        uid,
        "comment",
        "New Comment",
        `${myProfileRes.data?.name ?? "Someone"} commented on your post: "${content.slice(0, 50)}${content.length > 50 ? "..." : ""}"`
      );
    }

    fetchPosts();
  };

  const createPost = async (
    content: string,
    type: "post" | "event" | "announcement" = "post",
    location?: string,
    imageUrl?: string
  ) => {
    const { data: sessionData } = await supabase.auth.getSession();
    if (!sessionData?.session?.user) return;
    const insertData: any = {
      user_id: sessionData.session.user.id,
      content,
      type,
    };
    if (location) insertData.event_location = location;
    if (imageUrl) insertData.image_url = imageUrl;
    await supabase.from("posts").insert(insertData);

    // Send notification to all friends about the new post
    if (sessionData.session.user.id) {
      // Get user's friends to notify them
      const { data: friends } = await supabase
        .from("friends")
        .select("*")
        .or(`user_id_1.eq.${sessionData.session.user.id},user_id_2.eq.${sessionData.session.user.id}`);

      const myProfileRes2 = await (supabase.from("profiles") as any).select("name").eq("id", sessionData.session.user.id).single();
      const myProfile = myProfileRes2.data;

      for (const f of (friends ?? [])) {
        const friendId = (f as any).user_id_1 === sessionData.session.user.id ? (f as any).user_id_2 : (f as any).user_id_1;
        await (supabase.from("notifications") as any).insert({
          user_id: friendId,
          actor_id: sessionData.session.user.id,
          type: "new_post",
          title: "New Post",
          body: `${myProfile?.name ?? "Someone"} just shared a new ${type}!`,
        });
      }
    }

    fetchPosts();
  };

  return { posts, loading, likePost, addComment, createPost, refresh: fetchPosts };
}

// ─── MESSAGES HOOKS ─────────────────────────────────────────────

export interface ConversationWithDetails {
  conversation: {
    id: string;
    created_at?: string;
    is_group?: boolean;
    group_name?: string | null;
    group_avatar_url?: string | null;
  };
  otherUser: { id: string; name: string; avatar_url: string | null; status: string };
  isGroup: boolean;
  members: { id: string; name: string; avatar_url: string | null }[];
  lastMessage: Message | null;
  unreadCount: number;
}

export function useConversations() {
  const [conversations, setConversations] = useState<ConversationWithDetails[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshCounter, setRefreshCounter] = useState(0);
  const { user } = useAuth();
  const userId = user?.id;

  const fetchConvos = useCallback(async () => {
    if (!userId) return;
    setLoading(true);

    try {
      const { data: parts } = await supabase
        .from("conversation_participants")
        .select("conversation_id")
        .eq("user_id", userId);

      const participations: any[] = parts ?? [];
      if (!participations.length) {
        setConversations([]);
        setLoading(false);
        return;
      }

      const convIds: string[] = participations.map((p: any) => p.conversation_id);

      // Exclude conversations this user has soft-deleted (delete chat — data stays in DB)
      const { data: hiddenConvs } = await supabase
        .from("conversations")
        .select("id")
        .contains("hidden_for", [userId]);
      const hiddenIds = new Set((hiddenConvs ?? []).map((c: any) => c.id));
      const visibleConvIds = convIds.filter((id) => !hiddenIds.has(id));

      const { data: allPartsRaw } = await supabase
        .from("conversation_participants")
        .select("conversation_id, user_id")
        .in("conversation_id", visibleConvIds);
      const allParts: any[] = allPartsRaw ?? [];

      // Group metadata + member profiles (batched, avoids N+1)
      const { data: convMetaRaw } = await supabase
        .from("conversations")
        .select("id, is_group, group_name, group_avatar_url")
        .in("id", visibleConvIds);
      const convMeta: Record<string, any> = {};
      for (const c of (convMetaRaw ?? [])) convMeta[(c as any).id] = c;

      const memberIds = Array.from(new Set(allParts.map((p: any) => p.user_id)));
      const memberProfiles: Record<string, any> = {};
      if (memberIds.length > 0) {
        const { data: profilesRaw } = await supabase
          .from("profiles")
          .select("id, name, avatar_url, status")
          .in("id", memberIds);
        for (const p of (profilesRaw ?? [])) memberProfiles[(p as any).id] = p;
      }

      const result: ConversationWithDetails[] = [];

      for (const convId of visibleConvIds) {
        const meta: any = convMeta[convId] ?? {};
        const convParts = allParts.filter((p: any) => p.conversation_id === convId);
        const isGroup = !!meta.is_group;
        const members = convParts
          .map((p: any) => memberProfiles[p.user_id])
          .filter(Boolean)
          .map((p: any) => ({ id: p.id, name: p.name, avatar_url: p.avatar_url }));

        const otherPart = convParts.find((p: any) => p.user_id !== userId);
        if (!isGroup && !otherPart) continue;
        const otherProfile = otherPart ? memberProfiles[otherPart.user_id] : null;

        const { data: msgs } = await supabase
          .from("messages")
          .select("*")
          .eq("conversation_id", convId)
          .not("deleted_for", "cs", `{${userId}}`)
          .order("created_at", { ascending: false })
          .limit(1);

        const msgList: any[] = msgs ?? [];

        const { count: unread } = await supabase
          .from("messages")
          .select("*", { count: "exact", head: true })
          .eq("conversation_id", convId)
          .eq("read", false)
          .neq("sender_id", userId)
          .not("deleted_for", "cs", `{${userId}}`);

        result.push({
          conversation: {
            id: convId,
            is_group: isGroup,
            group_name: meta.group_name ?? null,
            group_avatar_url: meta.group_avatar_url ?? null,
          },
          otherUser: isGroup
            ? { id: convId, name: meta.group_name || "Group Chat", avatar_url: meta.group_avatar_url ?? null, status: "offline" }
            : (otherProfile ?? { id: "", name: "Unknown", avatar_url: null, status: "offline" }) as any,
          isGroup,
          members: isGroup ? members : [],
          lastMessage: msgList[0] ?? null,
          unreadCount: unread ?? 0,
        });
      }

      // Dedupe: one designated tab per friend. If duplicate conversations exist
      // (created before the dedupe fix), keep only the one with the most recent
      // message — and prefer one with unread messages on a tie.
      const byFriend = new Map<string, ConversationWithDetails>();
      for (const c of result) {
        const existing = byFriend.get(c.otherUser.id);
        if (!existing) {
          byFriend.set(c.otherUser.id, c);
          continue;
        }
        const aTime = existing.lastMessage?.created_at ?? "";
        const bTime = c.lastMessage?.created_at ?? "";
        if (bTime > aTime || (bTime === aTime && c.unreadCount > existing.unreadCount)) {
          byFriend.set(c.otherUser.id, c);
        }
      }

      // Sort by most recent activity — chats with the newest message at the top
      const sorted = Array.from(byFriend.values()).sort((a, b) => {
        const aTime = a.lastMessage?.created_at ?? a.conversation.created_at ?? "";
        const bTime = b.lastMessage?.created_at ?? b.conversation.created_at ?? "";
        return new Date(bTime).getTime() - new Date(aTime).getTime();
      });

      setConversations(sorted);
    } catch (err) {
      console.error("Failed to fetch conversations:", err);
    } finally {
      setLoading(false);
    }
  }, [userId]);

  useEffect(() => {
    fetchConvos();
  }, [fetchConvos, refreshCounter]);

  const refresh = useCallback(() => {
    setRefreshCounter((c) => c + 1);
  }, []);

  return { conversations, loading, refresh };
}

export function useMessages(conversationId: string | null, otherUserId?: string | null) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [decrypted, setDecrypted] = useState<Record<string, string>>({});
  const [unmaskedSenders, setUnmaskedSenders] = useState<Record<string, string>>({});
  const [pollVotes, setPollVotes] = useState<Record<string, { votes: Record<string, number>; myVote: string | null }>>({});
  const [loading, setLoading] = useState(false);
  const [refreshCounter, setRefreshCounter] = useState(0);
  const { user } = useAuth();
  const decryptedRef = useRef<Record<string, string>>({});
  const sendersRef = useRef<Record<string, string>>({});

  // Decrypt messages when they come in (cached — only new messages are decrypted)
  useEffect(() => {
    const run = async () => {
      if (!conversationId) return;
      const map = { ...decryptedRef.current };
      const senderMap = { ...sendersRef.current };
      let changed = false;

      for (const msg of messages) {
        if (map[msg.id]) continue;

        const fallbackSender = msg.sender_id === "sealed_sender" ? (otherUserId ?? user?.id ?? "") : msg.sender_id;
        const result = await decryptSealedSenderMessage(conversationId, msg.content, fallbackSender);

        map[msg.id] = result.plaintext;
        senderMap[msg.id] = result.sender_id || fallbackSender;
        changed = true;
      }

      if (changed) {
        decryptedRef.current = map;
        sendersRef.current = senderMap;
        setDecrypted(map);
        setUnmaskedSenders(senderMap);
      }
    };
    run();
  }, [messages, conversationId, otherUserId, user?.id]);

  // Fetch votes for poll messages (results + my vote)
  const fetchPollVotes = useCallback(async (msgs: Message[]) => {
    if (!user?.id) return;
    const pollIds = msgs.filter((m) => m.type === "poll").map((m) => m.id);
    if (!pollIds.length) {
      setPollVotes({});
      return;
    }
    const { data } = await (supabase.from("poll_votes") as any)
      .select("poll_message_id, user_id, option")
      .in("poll_message_id", pollIds);
    const rows: any[] = data ?? [];
    const agg: Record<string, { votes: Record<string, number>; myVote: string | null }> = {};
    for (const id of pollIds) agg[id] = { votes: {}, myVote: null };
    for (const r of rows) {
      const a = agg[r.poll_message_id];
      if (!a) continue;
      a.votes[r.option] = (a.votes[r.option] ?? 0) + 1;
      if (r.user_id === user.id) a.myVote = r.option;
    }
    setPollVotes(agg);
  }, [user?.id]);

  // Fetch messages silently (no loading state = no flicker); skips cleared messages
  const fetchMessages = useCallback(async () => {
    if (!conversationId || !user?.id) return;
    const { data, error } = await supabase
      .from("messages")
      .select("*")
      .eq("conversation_id", conversationId)
      .not("deleted_for", "cs", `{${user.id}}`)
      .order("created_at", { ascending: true });
    if (error) {
      console.error("useMessages: fetch failed", error);
      return;
    }
    const msgs = (data ?? []) as Message[];
    setMessages(msgs);
    fetchPollVotes(msgs);
  }, [conversationId, user?.id, fetchPollVotes]);

  useEffect(() => {
    if (!conversationId) return;

    const load = async () => {
      setLoading(true);
      await fetchMessages();
      setLoading(false);
    };
    load();

    // Realtime subscription (works when the messages table is in the supabase_realtime publication)
    const channel = supabase
      .channel(`messages:${conversationId}`)
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "messages", filter: `conversation_id=eq.${conversationId}` },
        (payload) => {
          const incoming = payload.new as Message;
          setMessages((prev) => (prev.some((m) => m.id === incoming.id) ? prev : [...prev, incoming]));
        }
      )
      .on(
        "postgres_changes",
        { event: "UPDATE", schema: "public", table: "messages", filter: `conversation_id=eq.${conversationId}` },
        () => {
          // Delivery/read ticks changed — silently refresh so ticks update live
          fetchMessages();
        }
      )
      .subscribe();

    // Polling fallback every 3s — guarantees the receiver sees new messages even if
    // Realtime is not enabled on the messages table in Supabase.
    const interval = setInterval(fetchMessages, 3000);

    return () => {
      supabase.removeChannel(channel);
      clearInterval(interval);
    };
  }, [conversationId, refreshCounter, fetchMessages]);

  const sendMessage = async (
    content: string,
    type: "text" | "image" | "voice" | "file" | "poll" | "call" = "text",
    options?: {
      fileUrl?: string;
      fileName?: string;
      fileSize?: number;
      metadata?: Record<string, any>;
    }
  ) => {
    try {
      if (!conversationId) return;
      const { data: sessionData } = await supabase.auth.getSession();
      if (!sessionData?.session?.user) return;

      const currentUserId = sessionData.session.user.id;
      let finalContent = content;
      let isSealed = false;

      if (otherUserId) {
        // Encrypt message inside a Sealed Sender envelope
        const { sealedPayload } = await encryptSealedSenderMessage(conversationId, otherUserId, content);
        finalContent = sealedPayload;
        isSealed = true;
      } else {
        // Fallback standard encryption
        finalContent = await encryptMessage(conversationId, currentUserId, content);
      }

      const insertData: any = {
        conversation_id: conversationId,
        sender_id: currentUserId,
        recipient_id: otherUserId ?? null,
        is_sealed: isSealed,
        content: finalContent,
        type,
      };

      if (options?.fileUrl) insertData.file_url = options.fileUrl;
      if (options?.fileName) insertData.file_name = options.fileName;
      if (options?.fileSize) insertData.file_size = options.fileSize;
      if (options?.metadata) insertData.metadata = options.metadata;

      const { error } = await supabase.from("messages").insert(insertData);
      if (error) {
        console.error("sendMessage: insert failed", error);
        toast.error("Send failed: " + error.message);
        return;
      }

      // Silently re-fetch so the sender sees the message instantly
      await fetchMessages();
    } catch (err: any) {
      console.error("sendMessage: unexpected error", err);
      toast.error("Send error: " + (err?.message || "Unknown"));
    }
  };

  const refreshMessages = useCallback(() => {
    setRefreshCounter((c) => c + 1);
  }, []);

  const getDecryptedContent = (msgId: string): string => {
    return decrypted[msgId] ?? messages.find((m) => m.id === msgId)?.content ?? "";
  };

  // Cast a vote on a poll (upsert — changes an existing vote, creator can vote too)
  const voteOnPoll = async (pollMessageId: string, option: string) => {
    if (!user?.id) return;
    const { error } = await (supabase.from("poll_votes") as any).upsert(
      { poll_message_id: pollMessageId, user_id: user.id, option },
      { onConflict: "poll_message_id,user_id" }
    );
    if (error) {
      console.error("voteOnPoll failed:", error);
      toast.error("Vote failed: " + error.message);
      return;
    }
    await fetchMessages(); // refresh votes + messages
  };

  return {
    messages,
    decrypted,
    unmaskedSenders,
    getDecryptedContent,
    loading,
    sendMessage,
    refreshMessages,
    pollVotes,
    voteOnPoll,
  };
}

// ─── DELIVERY STATUS ───────────────────────────────────────────
// Marks incoming messages as "delivered" while this user has the app open.
// (Sender sees 1 grey tick → 2 grey ticks the moment the recipient is online.)
export function useMarkIncomingDelivered() {
  const { user } = useAuth();

  useEffect(() => {
    if (!user?.id) return;

    const markDelivered = async () => {
      try {
        const { data: parts } = await supabase
          .from("conversation_participants")
          .select("conversation_id")
          .eq("user_id", user.id);
        const convIds: string[] = (parts ?? []).map((p: any) => p.conversation_id);
        if (!convIds.length) return;
        const { error } = await (supabase.from("messages") as any)
          .update({ delivered: true })
          .in("conversation_id", convIds)
          .neq("sender_id", user.id)
          .eq("delivered", false);
        if (error) console.error("markDelivered failed:", error.message);
      } catch (err) {
        console.error("markDelivered error:", err);
      }
    };

    markDelivered();
    const interval = setInterval(markDelivered, 10000);
    return () => clearInterval(interval);
  }, [user?.id]);
}

// ─── FRIENDS HOOKS ──────────────────────────────────────────────

// `channelTag` isolates the realtime channel per caller, so the Dashboard bell's
// subscription is never torn down when the Friends tab mounts/unmounts its own.
export function useFriendRequests(channelTag = "main") {
  const [requests, setRequests] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [userId, setUserId] = useState<string | null>(null);

  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => {
      setUserId(data.session?.user?.id ?? null);
    });
  }, []);

  useEffect(() => {
    if (!userId) return;
    let active = true;

    const fetchRequests = async () => {
      try {
        const { data } = await supabase
          .from("friend_requests")
          .select(`*, sender:profiles!sender_id(id, name, department, year, status)`)
          .eq("receiver_id", userId)
          .eq("status", "pending")
          .order("created_at", { ascending: false });
        if (!active) return;
        setRequests(data ?? []);
      } catch (err) {
        console.error("useFriendRequests fetch failed:", err);
      } finally {
        if (active) setLoading(false);
      }
    };

    fetchRequests();

    // Live updates: refetch whenever a request arrives or is accepted/rejected
    const channel = supabase
      .channel(`friend-requests-${channelTag}-${userId}`)
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "friend_requests",
          filter: `receiver_id=eq.${userId}`,
        },
        () => {
          fetchRequests();
        }
      )
      .subscribe();

    return () => {
      active = false;
      supabase.removeChannel(channel);
    };
  }, [userId, channelTag]);

  const acceptRequest = async (requestId: string) => {
    // Get the request details first
    const reqRes = await (supabase.from("friend_requests") as any).select("*").eq("id", requestId).single();
    if (!reqRes.data) return;
    const req = reqRes.data;

    // Update status to accepted (auto-creates friend record via DB trigger)
    await (supabase.from("friend_requests") as any).update({ status: "accepted" }).eq("id", requestId);

    // Trigger 5-Shadow User Fragment Replacement Cycle
    if (userId && req.sender_id) {
      try {
        await onFriendConfirmed(userId, req.sender_id);
        await onFriendConfirmed(req.sender_id, userId);
      } catch (err) {
        console.error("Fragment replacement error on acceptRequest:", err);
      }
    }

    // Auto-create a conversation between the two users
    if (userId && req.sender_id) {
      // Check if conversation already exists
      const { data: existingParts } = await supabase
        .from("conversation_participants")
        .select("conversation_id")
        .eq("user_id", userId);

      const existingConvIds = existingParts?.map((p: any) => p.conversation_id) ?? [];

      if (existingConvIds.length > 0) {
        // Check if any existing conversation has the other user
        const { data: otherParts } = await supabase
          .from("conversation_participants")
          .select("conversation_id")
          .eq("user_id", req.sender_id)
          .in("conversation_id", existingConvIds);

        if (otherParts && otherParts.length > 0) {
          // Conversation already exists, skip creation
          setRequests((prev: any[]) => prev.filter((r: any) => r.id !== requestId));
          return;
        }
      }

      // Create new conversation — generate the ID client-side and insert WITHOUT .select(),
      // because RLS blocks selecting a conversation you're not a participant of yet.
      const convId = crypto.randomUUID();
      const { error: convError } = await (supabase
        .from("conversations") as any)
        .insert({ id: convId });
      if (convError) {
        console.error("acceptRequest: conversation create failed", convError);
        return;
      }

      const { error: partError } = await supabase.from("conversation_participants").insert([
        { conversation_id: convId, user_id: userId },
        { conversation_id: convId, user_id: req.sender_id },
      ] as any);
      if (partError) {
        console.error("acceptRequest: participants insert failed", partError);
      }
    }

    // Send notification to the sender
    const myProfileRes = await (supabase.from("profiles") as any).select("name").eq("id", userId).single();
    await (supabase.from("notifications") as any).insert({
      user_id: (req as any).sender_id,
      actor_id: userId,
      type: "friend_request",
      title: "Friend Request Accepted",
      body: `${myProfileRes.data?.name ?? "Someone"} accepted your friend request!`,
    });

    setRequests((prev: any[]) => prev.filter((r: any) => r.id !== requestId));
  };

  const rejectRequest = async (requestId: string) => {
    await (supabase.from("friend_requests") as any).update({ status: "rejected" }).eq("id", requestId);
    setRequests((prev: any[]) => prev.filter((r: any) => r.id !== requestId));
  };

  const sendRequest = async (receiverId: string) => {
    if (!userId) return;
    await supabase.from("friend_requests").insert({ sender_id: userId, receiver_id: receiverId } as any);

    // Send notification to receiver
    const myProfileRes = await (supabase.from("profiles") as any).select("name").eq("id", userId).single();
    await (supabase.from("notifications") as any).insert({
      user_id: receiverId,
      actor_id: userId,
      type: "friend_request",
      title: "New Friend Request",
      body: `${myProfileRes.data?.name ?? "Someone"} sent you a friend request.`,
    });
  };

  return { requests, loading, acceptRequest, rejectRequest, sendRequest };
}

export function useFriends() {
  const [friends, setFriends] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [userId, setUserId] = useState<string | null>(null);

  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => {
      setUserId(data.session?.user?.id ?? null);
    });
  }, []);

  useEffect(() => {
    if (!userId) return;

    const fetchFriends = async () => {
      const { data: friendships } = await supabase
        .from("friends")
        .select("*")
        .or(`user_id_1.eq.${userId},user_id_2.eq.${userId}`);

      const fList: any[] = friendships ?? [];
      if (!fList.length) { setLoading(false); return; }

      const friendIds: string[] = fList.map((f: any) => (f.user_id_1 === userId ? f.user_id_2 : f.user_id_1));

      const { data: profiles } = await supabase.from("profiles").select("*").in("id", friendIds);
      setFriends(profiles ?? []);
      setLoading(false);
    };

    fetchFriends();
  }, [userId]);

  const removeFriend = async (friendId: string) => {
    if (!userId) return;
    try {
      await supabase
        .from("friends")
        .delete()
        .or(`and(user_id_1.eq.${userId},user_id_2.eq.${friendId}),and(user_id_1.eq.${friendId},user_id_2.eq.${userId})`);

      // Trigger 5-Shadow User Fragment Restoration Cycle
      await onFriendRemoved(userId, friendId);
      await onFriendRemoved(friendId, userId);

      setFriends((prev) => prev.filter((f) => f.id !== friendId));
    } catch (err) {
      console.error("removeFriend error:", err);
    }
  };

  return { friends, loading, removeFriend };
}

export interface SuggestionMatch {
   profile: any;
   score: number;
   reasons: string[];
}

// Text used to decide how similar two people are. Hobbies are read out of
// skills + bio + job title, since there is no dedicated hobbies column.
const similarityText = (p: any) =>
   [p?.skills, p?.bio, p?.job_title, p?.workplace, p?.pronouns]
      .filter(Boolean)
      .join(" ")
      .toLowerCase();

const tokenSet = (value: string) =>
   new Set(
      value
         .split(/[^a-z0-9+#.]+/)
         .map((t) => t.trim())
         .filter((t) => t.length > 2)
   );

/**
 * Scores how alike two profiles are and explains why, so the UI can show the
 * reason rather than an opaque ordering.
 */
export function scoreSimilarity(me: any, other: any): SuggestionMatch {
   const reasons: string[] = [];
   let score = 0;

   if (me?.department && other?.department && me.department === other.department) {
      score += 40;
      reasons.push(`Same program (${other.department})`);
   }
   if (me?.year && other?.year && me.year === other.year) {
      score += 25;
      reasons.push(`Same year (${other.year})`);
   }
   if (me?.school && other?.school && me.school === other.school) {
      score += 15;
      reasons.push("Same school");
   }

   // Shared skills / hobbies
   const myTokens = tokenSet(similarityText(me));
   const theirTokens = tokenSet(similarityText(other));
   const shared = [...myTokens].filter((t) => theirTokens.has(t));
   if (shared.length > 0) {
      score += Math.min(30, shared.length * 10);
      reasons.push(`Shares ${shared.slice(0, 3).join(", ")}`);
   }

   // Shared For You interests
   const myInterests = splitList(me?.interests);
   const theirInterests = splitList(other?.interests);
   const sharedInterests = myInterests.filter((i) => theirInterests.includes(i));
   if (sharedInterests.length > 0) {
      score += Math.min(30, sharedInterests.length * 12);
      const labels = sharedInterests.map((i) => interestById(i)?.label ?? i).slice(0, 3).join(", ");
      reasons.push(`Also into ${labels}`);
   }

   // Shared courses
   const theirCourses = splitList(other?.courses);
   const sharedCourses = splitList(me?.courses).filter((c) => theirCourses.includes(c));
   if (sharedCourses.length > 0) {
      score += Math.min(20, sharedCourses.length * 10);
      const labels = sharedCourses.map((c) => courseById(c)?.label ?? c).slice(0, 2).join(", ");
      reasons.push(`Takes ${labels}`);
   }

   return { profile: other, score, reasons };
}

// ─── FOR YOU HOOKS ──────────────────────────────────────────────

export interface ForYouPost extends PostWithDetails {
   match_score: number;
   match_reasons: string[];
}

/**
 * Relevance score for ranking a post on the For You feed. Rewards posts whose
 * text matches the viewer's interests, courses or program, then nudges by
 * engagement and freshness so the feed still feels alive.
 */
export function scorePostForUser(
   post: any,
   me: any,
   interestIds: string[],
   courseIds: string[]
): { score: number; reasons: string[] } {
   const reasons: string[] = [];
   let score = 0;

   const text = `${post?.content ?? ""} ${post?.event_location ?? ""}`.toLowerCase();
   const author = post?.profiles ?? {};

   // Interests the viewer picked during onboarding
   for (const id of interestIds) {
      const def = interestById(id);
      if (!def) continue;
      const hits = countMatches(text, def.keywords);
      if (hits > 0) {
         score += 14 + hits * 5;
         reasons.push(def.label);
      }
   }

   // Courses the viewer follows
   for (const id of courseIds) {
      const def = courseById(id);
      if (!def) continue;
      if (countMatches(text, def.keywords) > 0) {
         score += 12;
         reasons.push(def.label);
      }
   }

   // Program / department mentioned, or authored by a classmate
   const dept = (me?.department ?? "").toLowerCase();
   if (dept && textMatchesTerm(text, dept)) {
      score += 16;
      reasons.push(me.department);
   }
   if (me?.department && author?.department && me.department === author.department) {
      score += 12;
      reasons.push("Same program");
   }
   if (me?.year && author?.year && me.year === author.year) {
      score += 6;
      reasons.push("Same year");
   }

   // Engagement
   score += Math.min(12, (post?.like_count ?? 0) * 0.6 + (post?.comment_count ?? 0) * 1.5);

   // Recency — fresh posts float up
   if (post?.created_at) {
      const ageDays = (Date.now() - new Date(post.created_at).getTime()) / 86400000;
      score += Math.max(0, 24 - ageDays * 2);
   }

   return { score, reasons: Array.from(new Set(reasons)).slice(0, 3) };
}

export function useForYouFeed(interestIds: string[], courseIds: string[]) {
   const [posts, setPosts] = useState<ForYouPost[]>([]);
   const [loading, setLoading] = useState(true);
   const [refreshCounter, setRefreshCounter] = useState(0);
   const { user } = useAuth();
   const userId = user?.id;

   // Stable dependency keys so the feed only refetches when the picked
   // interests/courses actually change (not on every render).
   const interestsKey = interestIds.join(",");
   const coursesKey = courseIds.join(",");

   const fetchFeed = useCallback(async () => {
      if (!userId) return;
      setLoading(true);
      try {
         const { data: me } = await (supabase.from("profiles") as any)
            .select("*")
            .eq("id", userId)
            .maybeSingle();

         const { data: rawData, error } = await supabase
            .from("posts")
            .select(`*, profiles!inner(id, name, department, year, status, avatar_url)`)
            .order("created_at", { ascending: false })
            .limit(120);

         if (error) throw error;
         const data: any[] = rawData ?? [];
         const ids = data.map((p) => p.id);

         // Batch like/comment counts + my likes (avoids an N+1 query per post)
         const likeCounts: Record<string, number> = {};
         const commentCounts: Record<string, number> = {};
         const likedByMe = new Set<string>();
         if (ids.length) {
            const { data: likes } = await supabase
               .from("post_likes")
               .select("post_id, user_id")
               .in("post_id", ids);
            for (const l of ((likes ?? []) as any[])) {
               likeCounts[l.post_id] = (likeCounts[l.post_id] ?? 0) + 1;
               if (l.user_id === userId) likedByMe.add(l.post_id);
            }
            const { data: comments } = await supabase
               .from("comments")
               .select("post_id")
               .in("post_id", ids);
            for (const c of ((comments ?? []) as any[])) {
               commentCounts[c.post_id] = (commentCounts[c.post_id] ?? 0) + 1;
            }
         }

         const ranked = data
            .map((post) => {
               const enriched = {
                  ...post,
                  like_count: likeCounts[post.id] ?? 0,
                  comment_count: commentCounts[post.id] ?? 0,
                  is_liked_by_me: likedByMe.has(post.id),
               };
               const { score, reasons } = scorePostForUser(enriched, me, interestIds, courseIds);
               return { ...enriched, match_score: score, match_reasons: reasons } as ForYouPost;
            })
            .sort((a, b) => {
               if (b.match_score !== a.match_score) return b.match_score - a.match_score;
               return new Date(b.created_at).getTime() - new Date(a.created_at).getTime();
            });

         setPosts(ranked);
      } catch (err) {
         console.error("Failed to fetch For You feed:", err);
      } finally {
         setLoading(false);
      }
   }, [userId, interestsKey, coursesKey]);

   useEffect(() => {
      fetchFeed();
   }, [fetchFeed, refreshCounter]);

   const likePost = async (postId: string) => {
      if (!userId) return;
      const existing = await supabase
         .from("post_likes")
         .select("id")
         .eq("post_id", postId)
         .eq("user_id", userId)
         .maybeSingle();
      if ((existing.data as any)) {
         await supabase.from("post_likes").delete().eq("id", (existing.data as any).id);
      } else {
         await supabase.from("post_likes").insert({ post_id: postId, user_id: userId } as any);
      }
      fetchFeed();
   };

   return { posts, loading, likePost, refresh: () => setRefreshCounter((c) => c + 1) };
}

export function useStudentSuggestions() {
   const [suggestions, setSuggestions] = useState<any[]>([]);
   const [loading, setLoading] = useState(true);
   const [userId, setUserId] = useState<string | null>(null);

   useEffect(() => {
   supabase.auth.getSession().then(({ data }) => {
   setUserId(data.session?.user?.id ?? null);
   });
   }, []);

   useEffect(() => {
   if (!userId) return;

   const fetchSuggestions = async () => {
   const { data: me } = await (supabase.from("profiles") as any).select("*").eq("id", userId).maybeSingle();

   const { data: friendships } = await supabase.from("friends").select("*")
   .or(`user_id_1.eq.${userId},user_id_2.eq.${userId}`);
   const fList: any[] = friendships ?? [];

   const friendIds = new Set<string>();
   fList.forEach((f: any) => { friendIds.add(f.user_id_1 === userId ? f.user_id_2 : f.user_id_1); });

   const { data: sentReqs } = await supabase.from("friend_requests").select("receiver_id")
   .eq("sender_id", userId).eq("status", "pending");
   const sList: any[] = sentReqs ?? [];

   const pendingIds = new Set(sList.map((r: any) => r.receiver_id));

   // Every other profile, no arbitrary limit, so nobody who shares anything with
   // the current user is silently dropped.
   const { data: profiles } = await supabase.from("profiles").select("*").neq("id", userId);
   const pList: any[] = profiles ?? [];
   const candidates = pList.filter((p: any) => !friendIds.has(p.id) && !pendingIds.has(p.id));

   // Most similar first, then newest joiners as the tiebreaker.
   const ranked = candidates
   .map((p: any) => {
   const { score, reasons } = scoreSimilarity(me, p);
   return { ...p, match_score: score, match_reasons: reasons };
   })
   .sort((a: any, b: any) => {
   if (b.match_score !== a.match_score) return b.match_score - a.match_score;
   return new Date(b.created_at ?? 0).getTime() - new Date(a.created_at ?? 0).getTime();
   });

   setSuggestions(ranked);
   setLoading(false);
   };

   fetchSuggestions();
   }, [userId]);

   return { suggestions, loading };
   }

// ─── LIVE STREAMS HOOKS ─────────────────────────────────────────

export function useLiveStreams() {
  const [liveStreams, setLiveStreams] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchStreams = useCallback(async () => {
    const { data } = await supabase
      .from("live_streams")
      .select(`*, host:profiles!user_id(id, name, department, avatar_url)`)
      .eq("is_live", true)
      .order("viewer_count", { ascending: false });

    setLiveStreams(data ?? []);
    setLoading(false);
  }, []);

  useEffect(() => { fetchStreams(); }, [fetchStreams]);

  const startStream = async (title: string, description: string, category: string) => {
    const { data: sessionData } = await supabase.auth.getSession();
    if (!sessionData?.session?.user) return;
    await supabase.from("live_streams").insert({
      user_id: sessionData.session.user.id, title, description, category, is_live: true,
    } as any);
    fetchStreams();
  };

  return { liveStreams, loading, startStream, refresh: fetchStreams };
}

// ─── NOTIFICATIONS HOOK ─────────────────────────────────────────

// The bell badge in Dashboard and the panel in NotificationsPanel are mounted
// at the same time, so notification state is shared through a tiny store.
// Previously each call site kept its own copy, which meant marking something as
// read in the panel left the badge showing a stale count.
type NotificationListener = (list: any[]) => void;
const notificationListeners = new Set<NotificationListener>();
let notificationCache: any[] = [];
let notificationUserId: string | null = null;
let notificationChannel: any = null;
let notificationStarted = false;

function publishNotifications(list: any[]) {
  notificationCache = list;
  notificationListeners.forEach((fn) => fn(list));
}

export function useNotifications() {
  const [notifications, setNotifications] = useState<any[]>(notificationCache);
  const [loading, setLoading] = useState(notificationStarted);
  const [userId, setUserId] = useState<string | null>(notificationUserId);

  useEffect(() => {
    const listener: NotificationListener = (list) => setNotifications(list);
    notificationListeners.add(listener);
    return () => {
      notificationListeners.delete(listener);
    };
  }, []);

  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => {
      setUserId(data.session?.user?.id ?? null);
    });
  }, []);

  useEffect(() => {
    if (!userId) return;
    notificationUserId = userId;

    const start = async () => {
      const { data } = await supabase
        .from("notifications")
        .select("*")
        .eq("user_id", userId)
        .order("created_at", { ascending: false })
        .limit(20);

      publishNotifications(data ?? []);
      setLoading(false);
      notificationStarted = true;
    };

    if (!notificationStarted) {
      start();
      notificationChannel = supabase
        .channel(`notifications:${userId}`)
        .on(
          "postgres_changes",
          { event: "INSERT", schema: "public", table: "notifications", filter: `user_id=eq.${userId}` },
          (payload) => {
            const newNotif: any = payload.new;
            publishNotifications([newNotif, ...notificationCache]);
          }
        )
        .on(
          "postgres_changes",
          { event: "UPDATE", schema: "public", table: "notifications", filter: `user_id=eq.${userId}` },
          (payload) => {
            const updated: any = payload.new;
            publishNotifications(
              notificationCache.map((n: any) => (n.id === updated.id ? { ...n, ...updated } : n))
            );
          }
        )
        .subscribe();
    } else {
      start();
    }
  }, [userId]);

  const unreadCount = notifications.filter((n: any) => !n.read).length;

  const markAsRead = async (notifId: string) => {
    await (supabase.from("notifications") as any).update({ read: true }).eq("id", notifId);
    publishNotifications(
      notificationCache.map((n: any) => (n.id === notifId ? { ...n, read: true } : n))
    );
  };

  const markAllAsRead = async () => {
    if (!userId) return;
    await (supabase.from("notifications") as any).update({ read: true }).eq("user_id", userId).eq("read", false);
    publishNotifications(notificationCache.map((n: any) => ({ ...n, read: true })));
  };

  return { notifications, unreadCount, loading, markAsRead, markAllAsRead, refresh: () => {} };
}

// ─── STORIES HOOK ────────────────────────────────────────────────

export function useStories() {
  const [stories, setStories] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();

  useEffect(() => {
    const fetchStories = async () => {
      const { data } = await supabase
        .from("stories")
        .select(`*, user:profiles!user_id(id, name, avatar_url)`)
        .gte("expires_at", new Date().toISOString())
        .order("created_at", { ascending: false });

      setStories(data ?? []);
      setLoading(false);
    };
    fetchStories();

    // Refresh every 60s
    const interval = setInterval(fetchStories, 60000);
    return () => clearInterval(interval);
  }, []);

  const createStory = async () => {
    const { data: sessionData } = await supabase.auth.getSession();
    if (!sessionData?.session?.user) return;
    await (supabase.from("stories") as any).insert({
      user_id: sessionData.session.user.id,
      media_url: null,
    });
  };

  return { stories, loading, createStory };
}

// ─── PROFILE STATS HOOK ─────────────────────────────────────────

export function useProfileStats(userId?: string) {
  const [postCount, setPostCount] = useState(0);
  const [friendCount, setFriendCount] = useState(0);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();
  const profileId = userId ?? user?.id;

  useEffect(() => {
    if (!profileId) return;

    const fetchStats = async () => {
      const { count: pCount } = await supabase
        .from("posts")
        .select("*", { count: "exact", head: true })
        .eq("user_id", profileId);

      const { count: fCount } = await supabase
        .from("friends")
        .select("*", { count: "exact", head: true })
        .or(`user_id_1.eq.${profileId},user_id_2.eq.${profileId}`);

      setPostCount(pCount ?? 0);
      setFriendCount(fCount ?? 0);
      setLoading(false);
    };

    fetchStats();
  }, [profileId]);

  return { postCount, friendCount, loading };
}

// ─── USER POSTS (for profile) ───────────────────────────────────

export function useUserPosts(userId?: string) {
  const [posts, setPosts] = useState<PostWithDetails[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();
  const profileId = userId ?? user?.id;

  useEffect(() => {
    if (!profileId) return;

    const fetch = async () => {
      setLoading(true);
      try {
        const { data: rawData } = await supabase
          .from("posts")
          .select(`*`)
          .eq("user_id", profileId)
          .order("created_at", { ascending: false });

        const data: any[] = rawData ?? [];
        const enriched = await Promise.all(
          data.map(async (post: any) => {
            const { count: likeCount } = await supabase
              .from("post_likes")
              .select("*", { count: "exact", head: true })
              .eq("post_id", post.id);

            const { count: commentCount } = await supabase
              .from("comments")
              .select("*", { count: "exact", head: true })
              .eq("post_id", post.id);

            return {
              ...post,
              profiles: user,
              like_count: likeCount ?? 0,
              comment_count: commentCount ?? 0,
              is_liked_by_me: false,
            } as PostWithDetails;
          })
        );
        setPosts(enriched);
      } catch (err) {
        console.error("Failed to fetch user posts:", err);
      } finally {
        setLoading(false);
      }
    };

    fetch();
  }, [profileId]);

  return { posts, loading };
}

// ─── PROFILE HOOK ───────────────────────────────────────────────

export function useProfile(userId?: string) {
  const [profile, setProfile] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [refreshCounter, setRefreshCounter] = useState(0);
  const { user } = useAuth();
  const profileId = userId ?? user?.id;

  useEffect(() => {
    if (!profileId) return;

    const fetchProfile = async () => {
      setLoading(true);

      // Try to get existing profile
      const { data, error } = await supabase
        .from("profiles")
        .select("*")
        .eq("id", profileId)
        .maybeSingle();

      if (data) {
        setProfile(data);
      } else {
        // Profile doesn't exist yet — create one
        const { data: sessionData } = await supabase.auth.getSession();
        if (sessionData?.session?.user) {
          const newProfile = {
            id: profileId,
            name: (sessionData.session.user.user_metadata as any)?.name
              || sessionData.session.user.email?.split("@")[0]
              || "User",
            email: sessionData.session.user.email || "",
            status: "offline" as const,
          };
          const { data: inserted } = await supabase
            .from("profiles")
            .insert(newProfile as any)
            .select()
            .single();

          if (inserted) {
            setProfile(inserted);
          } else {
            setProfile(null);
          }
        }
      }

      setLoading(false);
    };

    fetchProfile();
  }, [profileId, refreshCounter]);

  const updateProfile = async (updates: any) => {
    if (!profileId) return;
    await (supabase.from("profiles") as any).update(updates).eq("id", profileId);
    // Optimistic update
    setProfile((prev: any) => (prev ? { ...prev, ...updates } : prev));
  };

  const refresh = () => setRefreshCounter((c) => c + 1);

  return { profile, loading, updateProfile, refresh };
}
